[2023-03-13 21:32:23,766] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available manual__2023-03-13T21:32:20.343258+00:00 [queued]>
[2023-03-13 21:32:23,774] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available manual__2023-03-13T21:32:20.343258+00:00 [queued]>
[2023-03-13 21:32:23,775] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:32:23,775] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-13 21:32:23,776] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:32:23,796] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-03-13 21:32:20.343258+00:00
[2023-03-13 21:32:23,807] {standard_task_runner.py:52} INFO - Started process 5356 to run task
[2023-03-13 21:32:23,820] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'is_api_available', 'manual__2023-03-13T21:32:20.343258+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp1y4swee1', '--error-file', '/tmp/tmp9y1gis5i']
[2023-03-13 21:32:23,825] {standard_task_runner.py:80} INFO - Job 99: Subtask is_api_available
[2023-03-13 21:32:23,918] {task_command.py:369} INFO - Running <TaskInstance: test.is_api_available manual__2023-03-13T21:32:20.343258+00:00 [running]> on host 5282528dd996
[2023-03-13 21:32:23,983] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T21:32:20.343258+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-13T21:32:20.343258+00:00
[2023-03-13 21:32:23,988] {http.py:97} INFO - Poking: api/
[2023-03-13 21:32:24,008] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2023-03-13 21:32:24,013] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-03-13 21:32:24,192] {base.py:301} INFO - Success criteria met. Exiting.
[2023-03-13 21:32:24,215] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=is_api_available, execution_date=20230313T213220, start_date=20230313T213223, end_date=20230313T213224
[2023-03-13 21:32:24,267] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-13 21:32:24,325] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
