[2023-03-13 21:25:03,527] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.store_user manual__2023-03-13T21:12:58.297213+00:00 [queued]>
[2023-03-13 21:25:03,537] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.store_user manual__2023-03-13T21:12:58.297213+00:00 [queued]>
[2023-03-13 21:25:03,538] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:25:03,538] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-13 21:25:03,539] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:25:03,550] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2023-03-13 21:12:58.297213+00:00
[2023-03-13 21:25:03,559] {standard_task_runner.py:52} INFO - Started process 4987 to run task
[2023-03-13 21:25:03,564] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'store_user', 'manual__2023-03-13T21:12:58.297213+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpr0q7nxd2', '--error-file', '/tmp/tmp225bm_ok']
[2023-03-13 21:25:03,566] {standard_task_runner.py:80} INFO - Job 97: Subtask store_user
[2023-03-13 21:25:03,638] {task_command.py:369} INFO - Running <TaskInstance: test.store_user manual__2023-03-13T21:12:58.297213+00:00 [running]> on host 5282528dd996
[2023-03-13 21:25:03,706] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T21:12:58.297213+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-13T21:12:58.297213+00:00
[2023-03-13 21:25:03,708] {postgres.py:127} INFO - Running copy expert: COPY users from stdin WITH DELIMITER AS ',', filename: /tmp/processed_user.csv
[2023-03-13 21:25:03,717] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2023-03-13 21:25:03,725] {python.py:173} INFO - Done. Returned value was: None
[2023-03-13 21:25:03,737] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=store_user, execution_date=20230313T211258, start_date=20230313T212503, end_date=20230313T212503
[2023-03-13 21:25:03,778] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-13 21:25:03,816] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
