[2023-03-13 22:05:03,096] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available scheduled__2023-03-13T22:00:00+00:00 [queued]>
[2023-03-13 22:05:03,103] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available scheduled__2023-03-13T22:00:00+00:00 [queued]>
[2023-03-13 22:05:03,104] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 22:05:03,104] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-13 22:05:03,105] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 22:05:03,114] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-03-13 22:00:00+00:00
[2023-03-13 22:05:03,123] {standard_task_runner.py:52} INFO - Started process 7040 to run task
[2023-03-13 22:05:03,127] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'is_api_available', 'scheduled__2023-03-13T22:00:00+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmplgd62f16', '--error-file', '/tmp/tmpkolw7j5g']
[2023-03-13 22:05:03,129] {standard_task_runner.py:80} INFO - Job 134: Subtask is_api_available
[2023-03-13 22:05:03,184] {task_command.py:369} INFO - Running <TaskInstance: test.is_api_available scheduled__2023-03-13T22:00:00+00:00 [running]> on host 5282528dd996
[2023-03-13 22:05:03,245] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T22:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T22:00:00+00:00
[2023-03-13 22:05:03,247] {http.py:97} INFO - Poking: api/
[2023-03-13 22:05:03,259] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2023-03-13 22:05:03,262] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-03-13 22:05:03,424] {base.py:301} INFO - Success criteria met. Exiting.
[2023-03-13 22:05:03,436] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=is_api_available, execution_date=20230313T220000, start_date=20230313T220503, end_date=20230313T220503
[2023-03-13 22:05:03,462] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-13 22:05:03,536] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
