[2023-03-13 21:32:28,023] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.store_user manual__2023-03-13T21:32:20.343258+00:00 [queued]>
[2023-03-13 21:32:28,028] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.store_user manual__2023-03-13T21:32:20.343258+00:00 [queued]>
[2023-03-13 21:32:28,029] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:32:28,029] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-13 21:32:28,029] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:32:28,036] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2023-03-13 21:32:20.343258+00:00
[2023-03-13 21:32:28,041] {standard_task_runner.py:52} INFO - Started process 5374 to run task
[2023-03-13 21:32:28,045] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'store_user', 'manual__2023-03-13T21:32:20.343258+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp2j9u67l2', '--error-file', '/tmp/tmpgbo881gp']
[2023-03-13 21:32:28,046] {standard_task_runner.py:80} INFO - Job 102: Subtask store_user
[2023-03-13 21:32:28,109] {task_command.py:369} INFO - Running <TaskInstance: test.store_user manual__2023-03-13T21:32:20.343258+00:00 [running]> on host 5282528dd996
[2023-03-13 21:32:28,166] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T21:32:20.343258+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-13T21:32:20.343258+00:00
[2023-03-13 21:32:28,168] {postgres.py:127} INFO - Running copy expert: COPY users from stdin WITH DELIMITER AS ',', filename: /tmp/processed_user.csv
[2023-03-13 21:32:28,177] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2023-03-13 21:32:28,184] {python.py:173} INFO - Done. Returned value was: None
[2023-03-13 21:32:28,195] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=store_user, execution_date=20230313T213220, start_date=20230313T213228, end_date=20230313T213228
[2023-03-13 21:32:28,218] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-13 21:32:28,240] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
