[2023-03-13 21:42:51,535] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.process_user scheduled__2023-03-13T21:35:00+00:00 [queued]>
[2023-03-13 21:42:51,544] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.process_user scheduled__2023-03-13T21:35:00+00:00 [queued]>
[2023-03-13 21:42:51,545] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:42:51,546] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-13 21:42:51,547] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:42:51,562] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): process_user> on 2023-03-13 21:35:00+00:00
[2023-03-13 21:42:51,569] {standard_task_runner.py:52} INFO - Started process 5895 to run task
[2023-03-13 21:42:51,574] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'process_user', 'scheduled__2023-03-13T21:35:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpcwqvwo7m', '--error-file', '/tmp/tmp3n1h27yd']
[2023-03-13 21:42:51,576] {standard_task_runner.py:80} INFO - Job 111: Subtask process_user
[2023-03-13 21:42:51,653] {task_command.py:369} INFO - Running <TaskInstance: test.process_user scheduled__2023-03-13T21:35:00+00:00 [running]> on host 5282528dd996
[2023-03-13 21:42:51,736] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T21:35:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T21:35:00+00:00
[2023-03-13 21:42:51,762] {python.py:173} INFO - Done. Returned value was: None
[2023-03-13 21:42:51,781] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=process_user, execution_date=20230313T213500, start_date=20230313T214251, end_date=20230313T214251
[2023-03-13 21:42:51,829] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-13 21:42:51,858] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
