[2022-10-18 06:13:32,898] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2022-10-18T06:13:27.731070+00:00 [queued]>
[2022-10-18 06:13:32,909] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2022-10-18T06:13:27.731070+00:00 [queued]>
[2022-10-18 06:13:32,910] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 06:13:32,912] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-18 06:13:32,913] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 06:13:32,924] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-10-18 06:13:27.731070+00:00
[2022-10-18 06:13:32,933] {standard_task_runner.py:52} INFO - Started process 2195 to run task
[2022-10-18 06:13:32,938] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2022-10-18T06:13:27.731070+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpzzpwyxh8', '--error-file', '/tmp/tmpc5iu4tuy']
[2022-10-18 06:13:32,941] {standard_task_runner.py:80} INFO - Job 66: Subtask store_user
[2022-10-18 06:13:32,991] {task_command.py:369} INFO - Running <TaskInstance: user_processing.store_user manual__2022-10-18T06:13:27.731070+00:00 [running]> on host 5282528dd996
[2022-10-18 06:13:33,047] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-10-18T06:13:27.731070+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-18T06:13:27.731070+00:00
[2022-10-18 06:13:33,049] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-10-18 06:13:33,056] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-18 06:13:33,062] {python.py:173} INFO - Done. Returned value was: None
[2022-10-18 06:13:33,070] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20221018T061327, start_date=20221018T061332, end_date=20221018T061333
[2022-10-18 06:13:33,118] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-18 06:13:33,142] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
