[2023-03-13 21:32:21,821] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.create_table manual__2023-03-13T21:32:20.343258+00:00 [queued]>
[2023-03-13 21:32:21,828] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.create_table manual__2023-03-13T21:32:20.343258+00:00 [queued]>
[2023-03-13 21:32:21,829] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:32:21,829] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-13 21:32:21,830] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:32:21,839] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2023-03-13 21:32:20.343258+00:00
[2023-03-13 21:32:21,848] {standard_task_runner.py:52} INFO - Started process 5353 to run task
[2023-03-13 21:32:21,854] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'create_table', 'manual__2023-03-13T21:32:20.343258+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpfip6l4hv', '--error-file', '/tmp/tmpqffud8ml']
[2023-03-13 21:32:21,856] {standard_task_runner.py:80} INFO - Job 98: Subtask create_table
[2023-03-13 21:32:21,951] {task_command.py:369} INFO - Running <TaskInstance: test.create_table manual__2023-03-13T21:32:20.343258+00:00 [running]> on host 5282528dd996
[2023-03-13 21:32:22,019] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T21:32:20.343258+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-13T21:32:20.343258+00:00
[2023-03-13 21:32:22,030] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2023-03-13 21:32:22,035] {dbapi.py:208} INFO - Running statement: 
            create table if not exists users(
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2023-03-13 21:32:22,036] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2023-03-13 21:32:22,047] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=create_table, execution_date=20230313T213220, start_date=20230313T213221, end_date=20230313T213222
[2023-03-13 21:32:22,070] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-13 21:32:22,133] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
