[2023-03-13 22:35:01,488] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.create_table scheduled__2023-03-13T22:30:00+00:00 [queued]>
[2023-03-13 22:35:01,499] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.create_table scheduled__2023-03-13T22:30:00+00:00 [queued]>
[2023-03-13 22:35:01,500] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 22:35:01,500] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-13 22:35:01,501] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 22:35:01,523] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2023-03-13 22:30:00+00:00
[2023-03-13 22:35:01,539] {standard_task_runner.py:52} INFO - Started process 8581 to run task
[2023-03-13 22:35:01,584] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'create_table', 'scheduled__2023-03-13T22:30:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpbs972vml', '--error-file', '/tmp/tmpezy7jz6w']
[2023-03-13 22:35:01,587] {standard_task_runner.py:80} INFO - Job 163: Subtask create_table
[2023-03-13 22:35:01,723] {task_command.py:369} INFO - Running <TaskInstance: test.create_table scheduled__2023-03-13T22:30:00+00:00 [running]> on host 5282528dd996
[2023-03-13 22:35:01,962] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T22:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T22:30:00+00:00
[2023-03-13 22:35:02,020] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2023-03-13 22:35:02,032] {dbapi.py:208} INFO - Running statement: 
            create table if not exists users(
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2023-03-13 22:35:02,034] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2023-03-13 22:35:02,070] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=create_table, execution_date=20230313T223000, start_date=20230313T223501, end_date=20230313T223502
[2023-03-13 22:35:02,172] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-13 22:35:02,344] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
