[2023-03-13 21:42:48,667] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available scheduled__2023-03-13T21:35:00+00:00 [queued]>
[2023-03-13 21:42:48,675] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.is_api_available scheduled__2023-03-13T21:35:00+00:00 [queued]>
[2023-03-13 21:42:48,676] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:42:48,676] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-13 21:42:48,676] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-13 21:42:48,687] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-03-13 21:35:00+00:00
[2023-03-13 21:42:48,701] {standard_task_runner.py:52} INFO - Started process 5889 to run task
[2023-03-13 21:42:48,721] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'is_api_available', 'scheduled__2023-03-13T21:35:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpdijcw9sm', '--error-file', '/tmp/tmp4gh74k4y']
[2023-03-13 21:42:48,723] {standard_task_runner.py:80} INFO - Job 109: Subtask is_api_available
[2023-03-13 21:42:48,818] {task_command.py:369} INFO - Running <TaskInstance: test.is_api_available scheduled__2023-03-13T21:35:00+00:00 [running]> on host 5282528dd996
[2023-03-13 21:42:49,045] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T21:35:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T21:35:00+00:00
[2023-03-13 21:42:49,059] {http.py:97} INFO - Poking: api/
[2023-03-13 21:42:49,084] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2023-03-13 21:42:49,088] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-03-13 21:42:49,300] {base.py:301} INFO - Success criteria met. Exiting.
[2023-03-13 21:42:49,337] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=is_api_available, execution_date=20230313T213500, start_date=20230313T214248, end_date=20230313T214249
[2023-03-13 21:42:49,383] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-13 21:42:49,484] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
